[build]
publish = "public"
command = "npm run build"

[build.environment]
NODE_VERSION = "14"

[[plugins]]
package = "netlify-plugin-checklinks"
  [plugins.inputs]
  skipPatterns = ["*.map"]
  checkExternal = true
